[package]
name = "ansion"
version = "0.1.0"
authors = ["Erich Gubler <erichdongubler@gmail.com>"]

[dependencies]
failure = "0.1.1"
log = "0.4.2"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.5"
features = ["consoleapi", "minwindef", "processenv", "winbase", "wincon", "winnt"]
